apiVersion: v1
kind: ServiceAccount
metadata:
  name: ansiblehelper
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: secret-creator
rules:
- apiGroups: [""]
  #
  # at the HTTP level, the name of the resource for accessing Secret
  # objects is "secrets"
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: create-secrets-global
subjects:
- kind: ServiceAccount
  name: ansiblehelper # Name is case sensitive
  namespace: ansible
roleRef:
  kind: ClusterRole
  name: secret-creator
  apiGroup: rbac.authorization.k8s.io